# Generated by Django 2.0 on 2018-04-14 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headimg', models.ImageField(upload_to='headimg')),
                ('tel', models.CharField(max_length=20)),
                ('QQ', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=10)),
                ('aboutme', models.CharField(max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userinfo', to='account.User')),
            ],
        ),
    ]
