# Generated by Django 2.0 on 2018-04-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='username',
            new_name='user',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default=2, max_length=7),
            preserve_default=False,
        ),
    ]
