# Generated by Django 2.0 on 2018-04-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_like_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like_num',
            name='user',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Like_num',
        ),
    ]
