# Generated by Django 2.0.5 on 2018-05-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180421_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='integral',
            field=models.IntegerField(default=0),
        ),
    ]
