# Generated by Django 2.0 on 2018-04-20 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_auto_20180415_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=50)),
                ('question_text', models.CharField(max_length=200)),
                ('question_date', models.DateTimeField(auto_now_add=True)),
                ('question_img', models.ImageField(upload_to='question_img')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.User')),
            ],
        ),
    ]
