# Generated by Django 2.0 on 2018-04-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_img',
            field=models.ImageField(null=True, upload_to='question_img'),
        ),
    ]
