# Generated by Django 2.0 on 2018-04-23 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180421_2013'),
        ('comment', '0003_like_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.IntegerField(default=0)),
                ('comment_text', models.TextField()),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment', to='account.User')),
                ('parent_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent', to='comment.comment')),
                ('reply_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reply', to='account.User')),
                ('root_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='root', to='comment.comment')),
            ],
        ),
    ]
