# Generated by Django 2.0 on 2018-04-30 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0012_auto_20180430_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history_record',
            options={'ordering': ['-view_time']},
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_img',
            field=models.ImageField(null=True, upload_to='answer_img'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent', to='comment.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='root_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='root', to='comment.Comment'),
        ),
    ]
