# Generated by Django 2.0 on 2018-05-08 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180421_2013'),
        ('comment', '0014_auto_20180430_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admire_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admire_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent', to='comment.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='root_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='root', to='comment.Comment'),
        ),
        migrations.AddField(
            model_name='admire_record',
            name='admire_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='comment.Comment'),
        ),
        migrations.AddField(
            model_name='admire_record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.User'),
        ),
    ]
