# Generated by Django 2.0 on 2018-05-15 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0016_auto_20180515_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='admire_record',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='comment.Question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admire_record',
            name='admire_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='comment.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent', to='comment.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='root_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='root', to='comment.Comment'),
        ),
    ]
