# Generated by Django 2.0.5 on 2018-06-03 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180602_1007'),
        ('comment', '0024_auto_20180602_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_read',
        ),
        migrations.AddField(
            model_name='admire_record',
            name='admire_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admire_who', to='account.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admire_record',
            name='admire_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='comment.Comment'),
        ),
        migrations.AlterField(
            model_name='admire_record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='who_admire', to='account.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent', to='comment.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='root_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='root', to='comment.Comment'),
        ),
    ]
